export const PERMISSIONS: Record<string, string[]> = {
  dashboard: ['view'],
  department: ['create', 'read', 'view', 'update', 'delete', 'manage'],
  designation: ['create', 'read', 'view', 'update', 'delete', 'manage'],
  employee: [
    'create',
    'read',
    'view',
    'update',
    'assignRole',
    'delete',
    'manage',
  ],
  role: [
    'create',
    'read',
    'view',
    'update',
    'delete',
    'assignPermissions',
    'manage',
  ],
  profile: ['view', 'update'],
  leave: ['create', 'read', 'view', 'update', 'delete', 'approve', 'manage'],
  leaveType: ['create', 'read', 'view', 'update', 'delete', 'manage'],
  report: ['create', 'read', 'view', 'update', 'delete', 'manage'],
};
